#!/usr/bin/env node
/**
 * Downloads the theme's Arabic webfonts and generates the @font-face CSS
 * that points at the local copies.
 *
 * The event runs offline, so the fonts must ship inside the build — a
 * CDN link would silently fall back to a system face on the day. Both
 * families are licensed under the SIL Open Font License 1.1, which
 * permits bundling; OFL.txt is downloaded alongside them.
 *
 * Google serves one @font-face per unicode subset (arabic, latin, …).
 * All of them are kept, with their `unicode-range` intact, so the browser
 * only downloads the subsets a screen actually needs.
 *
 * Usage: node scripts/fetch-fonts.mjs   (output is committed; re-run only
 * to refresh or add a weight)
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const fontsDir = resolve(root, 'public/themes/national-day/fonts')
const publicPath = '/themes/national-day/fonts'
const cssOut = resolve(root, 'src/theme/fonts.css')

// A modern UA is what makes Google Fonts serve woff2 rather than ttf.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

// IBM Plex Sans Arabic is the National Day 96 identity's secondary
// typeface (guideline §3.1). The primary, Saudi Font, is not openly
// licensed; add it here once the event is supplied with a web copy.
const FAMILIES = [{ slug: 'ibm-plex-sans-arabic', query: 'IBM+Plex+Sans+Arabic:wght@400;500;700' }]

/** Subsets worth shipping. Anything else is dropped to keep the build small. */
const KEEP_SUBSETS = new Set(['arabic', 'latin'])

async function get(url, asText = true) {
  const response = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`)
  return asText ? response.text() : Buffer.from(await response.arrayBuffer())
}

/** Splits Google's stylesheet into one record per @font-face block. */
function parseFaces(css) {
  const faces = []
  // Each block is preceded by a subset comment, e.g. `/* arabic */`.
  const pattern = /\/\*\s*([\w[\]-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g

  for (const [, subset, body] of css.matchAll(pattern)) {
    const family = body.match(/font-family:\s*'([^']+)'/)?.[1]
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1]
    const url = body.match(/url\(([^)]+)\)/)?.[1]
    const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)?.[1]

    if (family && weight && url) {
      faces.push({ subset, family, weight, url, unicodeRange: unicodeRange?.trim() })
    }
  }

  return faces
}

const blocks = []

await mkdir(fontsDir, { recursive: true })

for (const { slug, query } of FAMILIES) {
  const css = await get(`https://fonts.googleapis.com/css2?family=${query}&display=swap`)

  for (const face of parseFaces(css)) {
    if (!KEEP_SUBSETS.has(face.subset)) continue

    const fileName = `${slug}-${face.weight}-${face.subset}.woff2`
    await writeFile(resolve(fontsDir, fileName), await get(face.url, false))
    console.log(`  ${fileName}`)

    blocks.push(
      [
        '@font-face {',
        `  font-family: '${face.family}';`,
        '  font-style: normal;',
        `  font-weight: ${face.weight};`,
        '  font-display: swap;',
        `  src: url('${publicPath}/${fileName}') format('woff2');`,
        face.unicodeRange ? `  unicode-range: ${face.unicodeRange};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    )
  }
}

await writeFile(
  resolve(fontsDir, 'OFL.txt'),
  await get('https://raw.githubusercontent.com/google/fonts/main/ofl/ibmplexsansarabic/OFL.txt'),
)
console.log('  OFL.txt')

await writeFile(
  cssOut,
  [
    '/*',
    ' * Generated by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' *',
    ' * Local @font-face declarations for the theme\'s Arabic families, so',
    ' * the event machine never depends on a network it may not have.',
    ' */',
    '',
    ...blocks,
    '',
  ].join('\n'),
)
console.log(`\nWrote ${cssOut}`)
